<?xml version='1.0'?>

<robot name="myrobot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="cameraSize" value="0.05"/>
  <xacro:property name="cameraMass" value="0.15"/>
  <xacro:property name="wheeldiam" value="0.15" />
  <xacro:property name="wheel_separation" value="0.20"/>  
  <xacro:property name="M_PI" value="3.1415926535897931" />
  <xacro:property name="chassis_len" value="0.3" /> 

  <xacro:include filename="$(find mybot_description)/urdf/materials.xacro" />
  <xacro:include filename="$(find mybot_description)/urdf/mybot.gazebo.xacro" />


  <link name="base_link" />

  <!-- for robot base frame -->
  <link name='chassis'>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${chassis_len} ${wheel_separation - 0.05} .1"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <collision>
      <geometry>
        <box size="${chassis_len} ${wheel_separation - 0.05} .1"/>
      </geometry>
    </collision>

    <inertial>
      <mass value="15.0"/>
      <inertia
          ixx="0.5" ixy="0" ixz="0"
          iyy="1.0" iyz="0"
          izz="0.1"
      />
    </inertial>
  </link>

  <joint name="base_to_chassis_joint" type="fixed">
    <parent link="base_link"/>
    <child link="chassis"/>
    <origin xyz="0 0 ${wheeldiam/2}"/>
  </joint>


<!-- for caster -->
  <xacro:macro name="caster_visual" params="prefix reflect">
    <link name='${prefix}_caster_visual'>
      <visual>
        <geometry>
          <sphere radius="${wheeldiam/4}"/>
        </geometry>
      </visual>

      <collision>
        <geometry>
          <sphere radius="${wheeldiam/4}"/>
        </geometry>
        <surface>
          <friction>
            <ode>
              <mu>0</mu>
              <mu2>0</mu2>
              <slip1>1.0</slip1>
              <slip2>1.0</slip2>
            </ode>
          </friction>
        </surface>
      </collision>

      <inertial>
        <mass value="0.1"/>
        <origin xyz="0.0 0 0.1" rpy="0 0 0"/>
        <inertia
            ixx="0.5" ixy="0" ixz="0"
            iyy="1.0" iyz="0"
            izz="0.1"
        />
      </inertial>
    </link>

    <joint name="${prefix}_chassis_joint" type="fixed">
        <parent link="chassis"/>
        <child link="${prefix}_caster_visual"/>
        <origin xyz="${reflect*wheel_separation/2} 0 -${wheeldiam/4}"/>
    </joint>
  </xacro:macro>

  <xacro:caster_visual prefix="front" reflect="1"/>
  <xacro:caster_visual prefix="back" reflect="-1"/>


<!-- for wheel -->
  <xacro:macro name="wheel" params="prefix reflect">

    <link name="${prefix}_wheel">
      <visual>
        <origin xyz="0 0 0" rpy="${M_PI/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheeldiam/2}" length="0.025"/>
        </geometry>
        <material name="blue"/>
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="${M_PI/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheeldiam/2}" length="0.05"/>
        </geometry>
      </collision>

      <inertial>
        <origin xyz="0 0 0" rpy="${M_PI/2} 0 0"/>
        <mass value="2.5"/>
        <cylinder_inertia m="5" r="0.1" h="0.05"/>
        <inertia
          ixx="1.0" ixy="0.0" ixz="0.0"
          iyy="1.0" iyz="0.0"
          izz="1.0"/>
      </inertial>
    </link>

    <joint name="${prefix}_wheel_hinge" type="continuous">
      <origin xyz="0 ${reflect*wheel_separation/2} 0" rpy="0 0 0"/>
      <child link="${prefix}_wheel"/>
      <parent link="chassis"/>
      <axis xyz="0 1 0" rpy="0 0 0"/>
      <limit effort="100" velocity="100"/>
      <joint_properties damping="0.0" friction="0.0"/>
    </joint>

  </xacro:macro>

  <xacro:wheel prefix="right" reflect="-1" />
  <xacro:wheel prefix="left" reflect="1" />


  <!-- for camera  -->
  <link name="camera">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${cameraSize} ${cameraSize} ${cameraSize}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${cameraSize} ${cameraSize} ${cameraSize}"/>
      </geometry>
      <material name="green"/>
    </visual>

    <inertial>
      <mass value="${cameraMass}" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <box_inertia m="${cameraMass}" x="${cameraSize}" y="${cameraSize}" z="${cameraSize}" />
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>

  </link>

  <joint name="camera_joint" type="fixed">
    <axis xyz="0 1 0" />
    <origin xyz="${wheel_separation/2} 0 ${0.05 + cameraSize/2}" rpy="0 0 0"/>
    <parent link="chassis"/>
    <child link="camera"/>
  </joint>

  <!-- Hokuyo Laser -->
  <link name="hokuyo">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://mybot_description/meshes/hokuyo.dae"/>
      </geometry>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.1 0.1 0.1"/>
      </geometry>
    </collision>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>

  </link>

  <joint name="hokuyo_joint" type="fixed">
    <axis xyz="0 1 0" />
    <origin xyz="${wheel_separation/2} 0 ${0.1}" rpy="0 0 0"/>
    <parent link="chassis"/>
    <child link="hokuyo"/>
  </joint>

</robot>