<?xml version='1.0'?>

<robot name="myrobot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="cameraSize" value="0.05"/>
  <xacro:property name="cameraMass" value="0.1"/>
  <xacro:property name="wheeldiam" value="0.2" />
  <xacro:property name="wheel_separation" value="0.34"/>  
  <xacro:property name="M_PI" value="3.1415926535897931" />
  <xacro:property name="body_len" value="0.5" />

  <xacro:include filename="$(find indoor_ros)/urdf/color.xacro" />
  <xacro:include filename="$(find indoor_ros)/urdf/indoor_mobot.gazebo" />

  <link name="base_link" />

  <!-- for robot base frame -->
  <link name='body_frame'>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${body_len} .3 .2"/>
      </geometry>
      <material name="blue"/>
    </visual>

    <collision>
      <geometry>
        <box size="${body_len} .3 .2"/>
      </geometry>
    </collision>

    <inertial>
      <mass value="10.0"/>
      <inertia
          ixx="0.5" ixy="0" ixz="0"
          iyy="1.0" iyz="0"
          izz="0.1"
      />
    </inertial>
  </link>

  <joint name="body_frame_joint" type="fixed">
    <parent link="base_link"/>
    <child link="body_frame"/>
    <origin xyz="0 0 0.2"/>
  </joint>

<!-- body rect -->
  <xacro:macro name="rect" params="prefix size_x size_y size_z place_x joint_z">
    <link name='${prefix}_rect'>
      <visual>
        <origin xyz="${place_x} 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${size_x} ${size_y} ${size_z}"/>
        </geometry>
        <material name="white"/>
      </visual>

      <collision>
        <geometry>
           <box size="${size_x} ${size_y} ${size_z}"/>
        </geometry>
      </collision>

      <inertial>
        <mass value="10.0"/>
        <inertia
            ixx="0.5" ixy="0" ixz="0"
            iyy="1.0" iyz="0"
            izz="0.1"
        />
      </inertial>
    </link>

    <joint name="${prefix}_rect_joint" type="fixed">
      <parent link="body_frame"/>
      <child link="${prefix}_rect"/>
      <origin xyz="0 0 ${joint_z}"/>
    </joint>

  </xacro:macro>

  <xacro:rect prefix="first" size_x="${body_len-0.1}" size_y=".2" size_z=".05" place_x="0" joint_z="0.12"/>
  <xacro:rect prefix="second" size_x="${body_len-0.42}" size_y=".05" size_z=".04" place_x="0" joint_z="0.16"/>
  <xacro:rect prefix="third" size_x="${body_len-0.49}" size_y="0.01" size_z="0.27" place_x="-0.22" joint_z="0.23"/>
  
  <xacro:macro name="head">
    <link name="head_link">
      <visual>
          <geometry>
                <sphere radius="0.05"/>
          </geometry>
            <material name="white"/>
      </visual>
      <collision>
          <geometry>
                <sphere radius="0.05"/>
          </geometry>
      </collision>

      <inertial>
          <mass value="1"/>
          <inertia
              ixx="0.5" ixy="0" ixz="0"
              iyy="1.0" iyz="0"
              izz="0.1"
          />
        </inertial>

    </link>
    <joint name="head_joint" type="fixed">
        <parent link="third_rect"/>
        <child link="head_link"/>
        <origin xyz="-0.22 0 0.18"/>
    </joint>
  </xacro:macro>
  <xacro:head />

  <!-- for wheel -->
  <xacro:macro name="wheel" params="prefix reflect">
    <link name="${prefix}_wheel">
      <visual>
        <origin xyz="0 0 0" rpy="${M_PI/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheeldiam/2}" length="0.025"/>
        </geometry>
        <material name="white"/>
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="${M_PI/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheeldiam/2}" length="0.05"/>
        </geometry>
      </collision>

      <inertial>
        <origin xyz="0 0 0" rpy="${M_PI/2} 0 0"/>
        <mass value="2.5"/>
        <cylinder_inertia m="5" r="0.1" h="0.05"/>
        <inertia
          ixx="1.0" ixy="0.0" ixz="0.0"
          iyy="1.0" iyz="0.0"
          izz="1.0"/>
      </inertial>
    </link>

    <joint name="${prefix}_wheel_hinge" type="continuous">
      <origin xyz="0 ${reflect*wheel_separation/2} -0.1" rpy="0 0 0"/>
      <child link="${prefix}_wheel"/>
      <parent link="body_frame"/>
      <axis xyz="0 1 0" rpy="0 0 0"/>
      <limit effort="100" velocity="100"/>
      <joint_properties damping="0.0" friction="0.0"/>
    </joint>

  </xacro:macro>

  <xacro:wheel prefix="right" reflect="-1" />
  <xacro:wheel prefix="left" reflect="1" />


  <!-- for caster -->
  <xacro:macro name="caster_visual" params="prefix reflect">
    <link name='${prefix}_caster_visual'>
       <visual>
        <origin xyz="0 0 0" rpy="${M_PI/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheeldiam/2}" length="0.025"/>
        </geometry>
        <material name="black"/>
      </visual>

      <collision>
       <origin xyz="0 0 0" rpy="${M_PI/2} 0 0"/>
        <geometry>
           <cylinder radius="${wheeldiam/2}" length="0.025"/>
        </geometry>
        <surface>
          <friction>
            <ode>
              <mu>0</mu>
              <mu2>0</mu2>
              <slip1>1.0</slip1>
              <slip2>1.0</slip2>
            </ode>
          </friction>
        </surface>
      </collision>

      <inertial>
        <mass value="1.0"/>
        <origin xyz="0.0 0 0.1" rpy="0 0 0"/>
        <inertia
            ixx="0.5" ixy="0" ixz="0"
            iyy="1.0" iyz="0"
            izz="0.1"
        />
      </inertial>
    </link>

    <joint name="${prefix}_chassis_joint" type="fixed">
        <parent link="body_frame"/>
        <child link="${prefix}_caster_visual"/>
        <origin xyz="${reflect*wheel_separation/2.5} 0 -${wheeldiam/2}"/>
    </joint>
  </xacro:macro>

  <xacro:caster_visual prefix="front" reflect="1"/>
  <xacro:caster_visual prefix="back" reflect="-1"/>


</robot>